name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/PortfolioPro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          cache-dependency-path: backend/PortfolioPro/pom.xml

      - name: Build Spring Boot application
        run: mvn clean package -DskipTests
